version: "3.3"

services:
  nginx:
    image: nginx:1.17-alpine
#    depends_on:
#      - php-fpm
    ports:
      - 5566:80
    volumes:
      - ./:/app
      - ./docker/nginx/logs:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .htpasswd:/etc/nginx/.htpasswd
    environment:
      - TZ=Asia/Tokyo

#  php-fpm:
#    build:
#      context: ./docker
#      dockerfile: php/Dockerfile
#      args:
#        - TZ=Asia/Tokyo
#    volumes:
#      - ./:/app
#      - ./docker/php/logs:/var/log/php
#      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
#    working_dir: /app
#    links:
#      - mysql

#  mysql:
#    image: mysql:5.7
#    volumes:
#      - mysql-store:/var/lib/mysql
#      #- ./docker/mysql/logs:/var/log/mysql
#      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
#    environment:
#      - MYSQL_DATABASE=monomoney
#      - MYSQL_USER=monomoney
#      - MYSQL_PASSWORD=1
#      - MYSQL_ROOT_PASSWORD=1111
#      - TZ=Asia/Tokyo
#    ports:
#      - 13300:3306

#volumes:
#  mysql-store:
